version: 2.1

orbs:
  initialize:   julesabr/initialize@dev:1
  dotnet:       julesabr/dotnet@dev:1
  nuget:        julesabr/nuget@dev:1
  autoversion:  julesabr/autoversion@dev:2

workflows:
  main:
    when:
      equal: [ << pipeline.git.branch >>, main ]
    jobs:
      - initialize/checkout
      - autoversion/init:
          release-branch: main
          requires:
            - initialize/checkout
      - dotnet/test:
          project-file: Julesabr.Wrappers.csproj
          requires:
            - initialize/checkout
      - dotnet/pack:
          lib-name: Julesabr.Wrappers
          version-file: version
          project-file: Julesabr.Wrappers.csproj
          requires:
            - autoversion/init
            - dotnet/test
      - nuget/deploy:
          pkg-file: bin/dotnet/pack/*.nupkg
          api-key: $NUGET_KEY
          requires:
            - dotnet/pack
      - autoversion/publish:
          requires:
            - nuget/deploy
  develop:
    when:
      equal: [ << pipeline.git.branch >>, develop ]
    jobs:
      - initialize/checkout
      - autoversion/init:
          release-branch: main
          prerelease-branch: develop
          asset-path: bin/dotnet/pack
          requires:
            - initialize/checkout
      - dotnet/test:
          project-file: Julesabr.Wrappers.csproj
          requires:
            - initialize/checkout
      - dotnet/pack:
          lib-name: Julesabr.Wrappers
          version-file: version
          project-file: Julesabr.Wrappers.csproj
          requires:
            - autoversion/init
            - dotnet/test
      - nuget/deploy:
          pkg-file: bin/dotnet/pack/*.nupkg
          api-key: $NUGET_KEY
          requires:
            - dotnet/pack
      - autoversion/publish:
          requires:
            - nuget/deploy
  feature:
    when:
      or:
        - matches: { pattern: "^feature.*$", value: "<< pipeline.git.branch >>" }
        - matches: { pattern: "^hotfix.*$", value: "<< pipeline.git.branch >>" }
    jobs:
      - initialize/checkout
      - dotnet/test:
          project-file: Julesabr.Wrappers.csproj
          requires:
            - initialize/checkout
      - dotnet/pack:
          lib-name: Julesabr.Wrappers
          project-file: Julesabr.Wrappers.csproj
          requires:
            - dotnet/test
