version: 2.1

orbs:
  initialize: julesabr/initialize@dev:first
  dotnet:     julesabr/dotnet@dev:first
  
jobs:
  list-output:
    docker:
      - image: alpine:3.16
    working_directory: workspace
    steps:
      - attach_workspace:
          at: .
      - run: ls -l bin
      - run: ls -l bin/dotnet/pack

workflows:
  main: 
    jobs:
      - initialize/checkout
      - dotnet/test:
          project-file: Julesabr.Wrappers.csproj
          requires:
            - initialize/checkout
      - dotnet/pack:
          lib-name: Julesabr.Wrappers
          project-file: Julesabr.Wrappers.csproj
          requires:
            - dotnet/test
      - list-output:
          requires:
            - dotnet/pack