version: 2.1

orbs:
  initialize:    julesabr/initialize@dev:5
  dotnet:        julesabr/dotnet@dev:3
  docfx:         julesabr/docfx@dev:2
  nuget:         julesabr/nuget@dev:2
  gh-pages:      julesabr/gh-pages@dev:2
  auto-version:  julesabr/auto-version@dev:2

workflows:
  main:
    when:
      equal: [ << pipeline.git.branch >>, main ]
    jobs:
      - initialize/checkout:
          repository-url: https://github.com/julesabr/Wrappers.git
          shallow-clone: no
          add-ssh-keys: no
      - auto-version/init:
          release-branch: main
          add-ssh-keys: no
          checkout: no
          attach-workspace: yes
          persist-to-workspace: yes
          requires:
            - initialize/checkout
      - dotnet/test:
          project-file: Julesabr.Wrappers.csproj
          checkout: no
          attach-workspace: yes
          requires:
            - initialize/checkout
      - dotnet/pack:
          lib-name: Julesabr.Wrappers
          version-file: version
          project-file: Julesabr.Wrappers.csproj
          checkout: no
          attach-workspace: yes
          persist-to-workspace: yes
          requires:
            - auto-version/init
            - dotnet/test
      - docfx/build:
          path: docs
          checkout: no
          attach-workspace: yes
          persist-to-workspace: yes
          requires:
            - auto-version/init
            - dotnet/test
      - approve-deploy:
          type: approval
          requires:
            - dotnet/pack
            - docfx/build
      - nuget/deploy:
          pkg-file: bin/dotnet/pack/*.nupkg
          api-key: $NUGET_KEY
          requires:
            - approve-deploy
      - gh-pages/deploy:
          path: docs/_site
          repository-url: https://github.com/julesabr/Wrappers.git
          add-ssh-keys: no
          requires:
            - approve-deploy
      - auto-version/publish:
          add-ssh-keys: no
          checkout: no
          attach-workspace: yes
          requires:
            - nuget/deploy
            - gh-pages/deploy
  develop:
    when:
      equal: [ << pipeline.git.branch >>, develop ]
    jobs:
      - initialize/checkout:
          repository-url: https://github.com/julesabr/Wrappers.git
          shallow-clone: no
          add-ssh-keys: no
      - auto-version/init:
          release-branch: main
          prerelease-branch: develop
          add-ssh-keys: no
          checkout: no
          attach-workspace: yes
          persist-to-workspace: yes
          requires:
            - initialize/checkout
      - dotnet/test:
          project-file: Julesabr.Wrappers.csproj
          checkout: no
          attach-workspace: yes
          requires:
            - initialize/checkout
      - dotnet/pack:
          lib-name: Julesabr.Wrappers
          version-file: version
          project-file: Julesabr.Wrappers.csproj
          checkout: no
          attach-workspace: yes
          persist-to-workspace: yes
          requires:
            - auto-version/init
            - dotnet/test
      - nuget/deploy:
          pkg-file: bin/dotnet/pack/*.nupkg
          api-key: $NUGET_KEY
          requires:
            - dotnet/pack
      - auto-version/publish:
          add-ssh-keys: no
          checkout: no
          attach-workspace: yes
          requires:
            - nuget/deploy
  feature:
    when:
      or:
        - matches: { pattern: "^feature.*$", value: "<< pipeline.git.branch >>" }
        - matches: { pattern: "^hotfix.*$", value: "<< pipeline.git.branch >>" }
    jobs:
      - initialize/checkout:
          repository-url: https://github.com/julesabr/Wrappers.git
          add-ssh-keys: no
      - dotnet/test:
          project-file: Julesabr.Wrappers.csproj
          checkout: no
          attach-workspace: yes
          requires:
            - initialize/checkout
      - dotnet/pack:
          lib-name: Julesabr.Wrappers
          project-file: Julesabr.Wrappers.csproj
          checkout: no
          attach-workspace: yes
          requires:
            - dotnet/test
