version: 2.1

orbs:
  dotnet: julesabr/dotnet@dev:first
  
jobs:
  list-output:
    docker:
      - image: alpine:3.16
    steps:
      - checkout
      - run: ls -l bin

workflows:
  main: 
    jobs:
      - dotnet/pack:
          display-name: Julesabr.Wrappers
          project-file: Julesabr.Wrappers.csproj
      - list-output:
          requires:
            - dotnet/pack