version: 2.1
#Test
orbs:
  dotnet: julesabr/dotnet@dev:first

workflows:
  main: 
    jobs:
      - dotnet/pack:
          display-name: Julesabr.Wrappers
          project-file: Julesabr.Wrappers.csproj